name: cldemo
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pyopencl
  - pocl
  - islpy
  - pip
  - pip:
    - git+https://github.com/inducer/pymbolic
    - git+https://github.com/inducer/loopy
    - git+https://github.com/inducer/f2py
